version: '3'
services:
# ==============================================================================
  web:
    image: verbral/php-c9:${PHP_VERSION:-7.2}-apache
    environment:
      APACHE_DOCUMENT_ROOT: ${PWD}/web
      GIT_USER_NAME:
      GIT_USER_EMAIL:
      WAKATIME_API_KEY:
    working_dir: ${PWD}
    volumes:
      - ${PWD}/:${PWD}
      - ~/.ssh:/home/web/.ssh
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:80
      - 8181:8181
    depends_on:
      - mysql
# ==============================================================================
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mysql:/var/lib/mysql
# ==============================================================================
volumes:
  mysql: