version: '3'
services:

  web:
    image: verbral/php-theia:${PHP_VERSION:-7.4}
    environment:
      APACHE_DOCUMENT_ROOT: ${PWD}/web
      GIT_USER_NAME:
      GIT_USER_EMAIL:
      WAKATIME_API_KEY:
    working_dir: ${PWD}
    volumes:
      - ${PWD}:${PWD}
      - ~/.ssh:/home/docker/.ssh
    ports:
      - 80
      - 3000
    depends_on:
      - mysql

  selenium:
    image: selenium/standalone-chrome

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
