name: Push on master

on:
  push:
    branches:
      - master

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - uses: marceloprado/has-changed-path@v1
        id: changed-dockerfile
        with:
          paths: Dockerfile

      # Looks like in the future we might need some image versioning here.
      - name: Build and push Docker images
        if: steps.changed-dockerfile.outputs.changed == 'true'
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u verbruggenalex --password-stdin
          docker build . --target ci --tag docker.pkg.github.com/verbruggenalex/watchdog_registry/ci
          docker push docker.pkg.github.com/verbruggenalex/watchdog_registry/ci

      - name: Setup environment
        run: |
          docker-compose up -d ci mysql selenium
          sleep 5

      - name: Composer install
        run: |
          docker-compose exec -T web composer install --no-progress --no-suggest --ansi

      - name: Static checks
        run: |
          docker-compose exec -T web grumphp run

      - name: Setup website
        run: |
          docker-compose exec -T web taskman drupal:site-setup
          docker-compose exec -T web taskman drupal:site-install

      - name: Test website
        run: |
          docker-compose exec -T web behat
