name: Push on master

on:
  push:
    branches:
      - master

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - uses: marceloprado/has-changed-path@v1
        id: changed-dockerfile
        with:
          paths: Dockerfile

      # Looks like in the future we might need some image versioning here.
      - name: Build and push Docker images
        if: steps.changed-dockerfile.outputs.changed == 'true'
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u verbruggenalex --password-stdin
          docker build . --target ci --tag docker.pkg.github.com/verbruggenalex/watchdog_registry/watchdog-registry-ci
          docker push docker.pkg.github.com/verbruggenalex/watchdog_registry/watchdog-registry-ci

      - name: Setup environment
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u verbruggenalex --password-stdin
          docker-compose up -d ci mysql selenium
          sleep 5

      - name: Cache Composer
        uses: actions/cache@v2
        with:
          path: |
            vendor/
            web/
          key: vendor-web-${{ hashFiles('composer.lock') }}

      - name: Composer install
        run: |
          ls -la
          docker-compose exec -T ci composer install --no-progress --ansi || ls -la

      - name: Static checks
        run: |
          docker-compose exec -T ci grumphp run

      - name: Setup website
        run: |
          docker-compose exec -T ci taskman drupal:site-setup
          docker-compose exec -T ci taskman drupal:site-install

      - name: Test website
        id: test-website
        run: |
          docker-compose exec -T ci taskman setup:behat -Ddrupal.base_url=http://ci
          docker-compose exec -T ci behat

      - name: Upload screenshots
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: screenshots
          path: tests/screenshots/*.png
          if-no-files-found: ignore
          retention-days: 1

